#!/usr/bin/env bash

#Download and install all dependencies
yarn
#Build src into bundle dir
yarn run build
#Copy node_modules into bundle dir
cp package.json bundle/
cd bundle
# install prod dependencies
yarn --production
#Zip bundle files
zip -qr bundle.zip .
mv bundle.zip ../
#Clean directories
cd ..
rm -r bundle
